- docs/contributing/code_contribution_best_practices.rst
Fixes #16 
Added code style and conventions for C++ and Python repositories.
> add code style and conventions

- docs/contact.rst
Added student and outreach program section under _Join the moja global family tab_.
Fixes # (issue)
> add student program section initial commit

- docs/prerequisites/cmake.rst
- docs/prerequisites/docker.rst
- docs/prerequisites/git.rst
- docs/prerequisites/vcpkg.rst
- docs/prerequisites/visual_studio.rst
Some minor suggestions for the Prerequisites section
> Prerequisites: describe the FLINT toolkit

- docs/DevelopmentSetup/git_and_github_guide.rst
- docs/DevelopmentSetup/index.rst
- docs/contributing/after_contribute.rst
- docs/contributing/before_contribute.rst
- docs/contributing/code_contribution_best_practices.rst
- docs/contributing/index.rst
- docs/contributing/ways_to_contribute.rst
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
...
> improve contributing section

- docs/contact.rst
Improved join us section by adding subsections - moja global slack and moja global outreach. Please suggest anything if missing and needs to be included.
Fixes #25 
> improve join us section

- docs/contributing/after_contribute.rst
Add help others contribute section.
Fixes #23 
> add help other contribute section

- docs/DeveloperWorkflow/index.rst
add index or introductory section for github workflow practices.
Fixes #31 
]
> add index section for github workflow practices

- docs/DevelopmentSetup/FLINT.example_installation.rst
- docs/DevelopmentSetup/docker_installation.rst
- docs/DevelopmentSetup/docker_installation_example.rst
- docs/DevelopmentSetup/visual_studio_example.rst
- docs/DevelopmentSetup/visual_studio_win_example.rst
- docs/DevelopmentSetup/windows_installation.rst
[WORK IN PROGRESS]
Added section for flint.example setup instructions. Also format the development setup other sections. 
Fixes #21 
> add flint.example setup and format

- docs/conf.py
- docs/requirements.txt
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #36 
> add copy buttons

- docs/DevelopmentSetup/index.rst
- docs/contact.rst
Add technical steering committee meetings and datasets sections.
Fixes #34 
> add tsc and datasets sections

- docs/faq.rst
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #40 
> WIP: add installation support faqs

- docs/DevelopmentSetup/git_and_github_guide.rst
- docs/GCBMDevelopmentSetup/windows_installation.rst
- docs/prerequisites/git.rst
This PR deals with issue #49.
And resolves all the dead links that were there in the master branch.
There were 14 dead links given in the issue, but it summarizes into 5 dead links in the master.
> Batch 1 and 2.

- docs/DeveloperWorkflow/reviewing.rst
- docs/contributing/code_contribution_best_practices.rst
Add section on writing documentation under code contribution best practices. Also corrected link in reviewing section to point to docs section.
Fixes #27 
> add section on writing documentation

- docs/DeveloperWorkflow/index.rst
> Change the topic to be GitHub workflow best practices

- docs/prerequisites/vcpkg.rst
Changed the command for vcpkg installation
Fixes #54
> command changed

- README.md
Added set up installation for Windows Users.
Fixes #90
> added set up env instructions for Windows Users

- docs/DocumentationStyleGuide/index.rst
- docs/DocumentationStyleGuide/language-grammar/abbreviations-acronymn.rst
- docs/DocumentationStyleGuide/language-grammar/articles.rst
- docs/DocumentationStyleGuide/language-grammar/capitalization.rst
- docs/DocumentationStyleGuide/style-tone.rst
This PR:
- Adds the Style Tone Guide
- Adds Grammar Docs for articles, capitalization, abbreviations and acronymns.
> DOCS: Add Style Tone Guide + Grammar Docs

- docs/DocumentationStyleGuide/index.rst
- docs/DocumentationStyleGuide/language-grammar/clauses.rst
- docs/DocumentationStyleGuide/language-grammar/conjunctions-contractions.rst
- docs/DocumentationStyleGuide/language-grammar/direct-indirect.rst
- docs/DocumentationStyleGuide/language-grammar/plurals.rst
- docs/DocumentationStyleGuide/language-grammar/possessives.rst
- docs/DocumentationStyleGuide/style-tone.rst
This PR:
- Adds docs for clauses
- Adds docs for conjunctions & contractions
- Adds docs for direct and indirect speech
- Adds docs for plurals
- Adds docs for possessives
> Add Language & Grammar Docs

- docs/index.rst
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Thanks for opening the Pull Request for moja global. Happy contributing ✨
> Added links in project documentation

- docs/faq.rst
- docs/index.rst
This PR:
- Add more relevant contact channels on the index page
-  Refactor docs in the FAQ page to make it more readable
This PR is a part of the documentation audit.
> Refactor index page and FAQ docs

- .readthedocs.yaml
- docs/requirements.txt
> CHORE: Upgrade Sphinx

- docs/Understanding-FLINT/moja-flint/operations.rst
Resolved typos in the Moja FLINT operations
> Resolved typos

- docs/Guidelines/DeveloperWorkflow/bots_and_integrations.rst
- docs/faq.rst
- docs/join-moja-global.rst
Demo PR to test [Codespell](https://github.com/codespell-project/codespell) for CI integration.
cc: @Namyalg
> chore: fix spell mistakes

- README.md
- docs/FLINT/FLINTDevelopmentSetup/FLINT.example_installation.rst
- docs/FLINT/FLINTDevelopmentSetup/docker_installation.rst
- docs/FLINT/FLINTDevelopmentSetup/docker_installation_example.rst
- docs/FLINT/FLINTDevelopmentSetup/git_and_github_guide.rst
- docs/FLINT/FLINTDevelopmentSetup/index.rst
- docs/FLINT/FLINTDevelopmentSetup/visual_studio_example.rst
- docs/FLINT/FLINTDevelopmentSetup/visual_studio_win_example.rst
- docs/FLINT/FLINTDevelopmentSetup/windows_installation.rst
- docs/FLINT/FLINTPrerequisites/git.rst
- docs/GCBM/GCBMDevelopmentSetup/windows_installation.rst
- docs/Guidelines/Contributing/after_contribute.rst
- docs/Guidelines/Contributing/before_contribute.rst
- docs/Guidelines/Contributing/code_contribution_best_practices.rst
- docs/Guidelines/Contributing/ways_to_contribute.rst
- docs/Guidelines/DeveloperWorkflow/reviewing.rst
- docs/faq.rst
- docs/join-moja-global.rst
Restructuring the documentation lead to a few broken links due to linking within the pages of the documentation. This PR fixes all broken links
Thanks for opening the Pull Request for moja global. Happy contributing ✨
> fix: broken links

- docs/GCBM/GCBMInputs/InvestigatingGCBMInputs/tables.rst
> docs: add schema descriptions for input_database

- docs/source/_static/css/custom.css
Improved Main Heading on [HomePage](https://docs.moja.global/en/master/) for smaller screen Devices.
> Improved Heading #203
